const cardsData = [
  {
    id: 0,
    name: "black-2Cutlass-1Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/black-2Cutlass-1Coin.png",
  },
  {
    id: 1,
    name: "black-4Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/black-4Cutlass-2Coin.png",
  },
  {
    id: 2,
    name: "black-7Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/black-7Cutlass-3Coin.png",
  },
  {
    id: 3,
    name: "black-skull-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/black-skull-3Coin.png",
  },
  {
    id: 4,
    name: "black-skull-4Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/black-skull-4Coin.png",
  },
  {
    id: 5,
    name: "blue-1Cutlass-1Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-1Cutlass-1Coin.png",
  },
  {
    id: 6,
    name: "blue-1Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-1Cutlass-2Coin.png",
  },
  {
    id: 7,
    name: "blue-2Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-2Cutlass-2Coin.png",
  },
  {
    id: 8,
    name: "blue-2Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-2Cutlass-3Coin.png",
  },
  {
    id: 9,
    name: "blue-5Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-5Cutlass-3Coin.png",
  },
  {
    id: 10,
    name: "blue-5Cutlass-4Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/blue-5Cutlass-4Coin.png",
  },
  {
    id: 11,
    name: "green-1Cutlass-1Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-1Cutlass-1Coin.png",
  },
  {
    id: 12,
    name: "green-1Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-1Cutlass-2Coin.png",
  },
  {
    id: 13,
    name: "green-3Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-3Cutlass-2Coin.png",
  },
  {
    id: 14,
    name: "green-3Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-3Cutlass-3Coin.png",
  },
  {
    id: 15,
    name: "green-5Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-5Cutlass-3Coin.png",
  },
  {
    id: 16,
    name: "green-5Cutlass-4Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/green-5Cutlass-4Coin.png",
  },
  {
    id: 17,
    name: "red-1Cutlass-1Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/red-1Cutlass-1Coin.png",
  },
  {
    id: 18,
    name: "red-3Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/red-3Cutlass-2Coin.png",
  },
  {
    id: 19,
    name: "red-6Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/red-6Cutlass-3Coin.png",
  },
  {
    id: 20,
    name: "red-skull-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/red-skull-3Coin.png",
  },
  {
    id: 21,
    name: "red-skull-4Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/red-skull-4Coin.png",
  },
  {
    id: 23,
    name: "yellow-1Cutlass-1Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-1Cutlass-1Coin.png",
  },
  {
    id: 24,
    name: "yellow-1Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-1Cutlass-2Coin.png",
  },
  {
    id: 25,
    name: "yellow-2Cutlass-2Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-2Cutlass-2Coin.png",
  },
  {
    id: 26,
    name: "yellow-2Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-2Cutlass-3Coin.png",
  },
  {
    id: 27,
    name: "yellow-4Cutlass-3Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-4Cutlass-3Coin.png",
  },
  {
    id: 28,
    name: "yellow-4Cutlass-4Coin.png",
    type: "ship",
    desc: "",
    cardUrl: "./assets/ships/yellow-4Cutlass-4Coin.png",
  },
];

export { cardsData };
